openapi: 3.0.0
x-stoplight:
  id: 6hf5i0fusa9fv
info:
  title: Dólar API Argentina
  version: '1.0'
  description: 'API desarrollada en EsJS (https://esjs.dev) para las diferentes cotizaciones de Dólar en Argentina'
  license:
    name: MIT
servers:
  - url: 'https://dolar-api-argentina.vercel.app/'
    description: Producción
  - url: 'http://localhost:3000'
    description: Local
paths:
  /v1/dolares:
    get:
      summary: Dólares
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolares
  /v1/dolares/oficial:
    get:
      summary: Dólar Oficial
      tags: []
      responses:
        '200':
          description: Cotización
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
          headers: {}
      operationId: get-dolar-oficial
  /v1/dolares/blue:
    get:
      summary: Dólar Blue
      tags: []
      responses:
        '200':
          description: Cotización
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-blue
    parameters: []
  /v1/dolares/bolsa:
    get:
      summary: Dólar Bolsa
      tags: [ ]
      responses:
        '200':
          description: Cotización
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-bolsa
    parameters: [ ]
  /v1/dolares/contadoconliqui:
    get:
      summary: Dólar Contado con liquidación
      tags: [ ]
      responses:
        '200':
          description: Cotización
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-contadoconliqui
    parameters: [ ]
  /v1/dolares/solidario:
    get:
      summary: Dólar Solidario (Turista)
      tags: [ ]
      responses:
        '200':
          description: Cotización
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-solidario
    parameters: [ ]
  /v1/dolares/mayorista:
    get:
      summary: Dólar Mayorista
      tags: []
      responses:
        '200':
          description: Cotización
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cotizacion'
      operationId: get-dolar-mayorista
    parameters: []
  /estado:
    get:
      summary: Estado de la API
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Estado'
      operationId: get-estado
components:
  schemas:
    Cotizacion:
      title: Cotizacion
      type: object
      x-stoplight:
        id: ce96aa7960850
      x-examples:
        Example 1:
          fecha: '2023-01-01T12:00:00.000Z'
          compra: 123.99
          venta: 132.99
      properties:
        compra:
          type: number
        venta:
          type: number
        casa:
          type: string
        nombre:
          type: string
        fechaActualizacion:
          type: string
      required:
        - compra
        - venta
        - fechaActualizacion
    Estado:
      title: Estado
      x-stoplight:
        id: ogwpb2wxiqwqh
      type: object
      properties:
        estado:
          type: string
        aleatorio:
          type: integer
      x-examples:
        Example 1:
          estado: Disponible
          aleatorio: 1234
